
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]
  # pull_request:
  #   branches: [ dev ]

jobs:
  build:

    runs-on: windows-latest


    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v2
    
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Get Previous tag
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0

    - name: Update package.json URL
      uses: jossef/action-set-json-field@v1
      with:
        file: package.json
        field: url
        value: ${{ secrets.URL_DEV }}

    - name: Update package.json VERSION
      uses: jossef/action-set-json-field@v1
      with:
        file: package.json
        field: version
        value: ${{ steps.previoustag.outputs.tag }}

    - name: Compile boberto launcher
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run build:all

    - name: Upload Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
       repo_token: "${{ secrets.GITHUB_TOKEN }}"
       automatic_release_tag: "${{ steps.previoustag.outputs.tag }}"
       prerelease: false
       title: "Development Build"
       files: |
        ./dist/*.zip
        ./dist/*.exe